# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ProductView.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(592, 672)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fme_card_content_0 = QtWidgets.QFrame(Form)
        self.fme_card_content_0.setMinimumSize(QtCore.QSize(570, 650))
        self.fme_card_content_0.setStyleSheet("")
        self.fme_card_content_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fme_card_content_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fme_card_content_0.setObjectName("fme_card_content_0")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.fme_card_content_0)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.fme_image_cap_2 = QtWidgets.QFrame(self.fme_card_content_0)
        self.fme_image_cap_2.setStyleSheet("QFrame {\n"
"    background-color : #CED7E6;\n"
"    border : 1px solid;\n"
"    border-color: #CED7E6;\n"
"    border-top-right-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}")
        self.fme_image_cap_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fme_image_cap_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fme_image_cap_2.setLineWidth(1)
        self.fme_image_cap_2.setMidLineWidth(0)
        self.fme_image_cap_2.setObjectName("fme_image_cap_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fme_image_cap_2)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fme_image = QtWidgets.QFrame(self.fme_image_cap_2)
        self.fme_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fme_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fme_image.setLineWidth(1)
        self.fme_image.setObjectName("fme_image")
        self.horizontalLayout.addWidget(self.fme_image)
        self.frame = QtWidgets.QFrame(self.fme_image_cap_2)
        self.frame.setMinimumSize(QtCore.QSize(280, 425))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color : #FFF;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_12 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("QFrame {\n"
"    border : none;\n"
"    border-color: transparent;\n"
"    border-top-right-radius: 0px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_24.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.lbl_card_title = QtWidgets.QLabel(self.frame_12)
        self.lbl_card_title.setStyleSheet("QLabel {\n"
"    margin-top : 12px;\n"
"    font : 18px \"Arial\";\n"
"    color: #34373B;\n"
"}")
        self.lbl_card_title.setObjectName("lbl_card_title")
        self.verticalLayout_24.addWidget(self.lbl_card_title)
        self.lbl_card_subtitle = QtWidgets.QLabel(self.frame_12)
        self.lbl_card_subtitle.setStyleSheet("QLabel {\n"
"    font : 18px \"Arial\";\n"
"    color: #A0A0A0;\n"
"}")
        self.lbl_card_subtitle.setObjectName("lbl_card_subtitle")
        self.verticalLayout_24.addWidget(self.lbl_card_subtitle)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame {\n"
"    border : none;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("QLabel {\n"
"    font : 18px \"Arial\";\n"
"    color: #A0A0A0;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.ted_message_2 = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ted_message_2.sizePolicy().hasHeightForWidth())
        self.ted_message_2.setSizePolicy(sizePolicy)
        self.ted_message_2.setAutoFillBackground(False)
        self.ted_message_2.setStyleSheet("QTextEdit {\n"
"    background-color: transparent;\n"
"    border : 1px solid;\n"
"    border-color: #CED7E6;\n"
"    border-radius: 7px;\n"
"    font : 17px \"Arial\";\n"
"}")
        self.ted_message_2.setReadOnly(True)
        self.ted_message_2.setObjectName("ted_message_2")
        self.verticalLayout_6.addWidget(self.ted_message_2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setStyleSheet("QFrame {\n"
"    border : none;\n"
"    border-color: transparent;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sbx_amount = QtWidgets.QSpinBox(self.frame_14)
        self.sbx_amount.setStyleSheet("QLineEdit, QTextEdit, QComboBox, QSpinBox, QDoubleSpinBox {\n"
"    background-color : transparent;\n"
"    border : 1px solid #DADDE1;\n"
"    border-radius : 5px;\n"
"    color : #616161;\n"
"    min-height : 40px;\n"
"    font : 77 18px \"Arial\";\n"
"}")
        self.sbx_amount.setObjectName("sbx_amount")
        self.verticalLayout_2.addWidget(self.sbx_amount)
        self.btn_add_to_cart = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_to_cart.sizePolicy().hasHeightForWidth())
        self.btn_add_to_cart.setSizePolicy(sizePolicy)
        self.btn_add_to_cart.setStyleSheet("QPushButton {\n"
"    color : #FFFFFF;\n"
"    border-style : solid;\n"
"    border-radius: 5px;\n"
"    min-height : 40px;\n"
"    font : 77 18px \"Arial\";\n"
"    background-color : #1877F2;\n"
"    padding-left : 20px;\n"
"    padding-right : 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #FFF;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color : transparent;\n"
"    color : #1877F2;\n"
"    border: 1px solid #1877F2;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.btn_add_to_cart.setObjectName("btn_add_to_cart")
        self.verticalLayout_2.addWidget(self.btn_add_to_cart)
        self.btn_buy = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_buy.sizePolicy().hasHeightForWidth())
        self.btn_buy.setSizePolicy(sizePolicy)
        self.btn_buy.setStyleSheet("QPushButton {\n"
"    color : #FFFFFF;\n"
"    border-style : solid;\n"
"    border-radius: 5px;\n"
"    min-height : 40px;\n"
"    font : 77 18px \"Arial\";\n"
"    background-color : #42B72A;\n"
"    padding-left : 20px;\n"
"    padding-right : 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #FFF;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color : transparent;\n"
"    color : #42B72A;\n"
"    border: 1px solid #42B72A;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.btn_buy.setObjectName("btn_buy")
        self.verticalLayout_2.addWidget(self.btn_buy)
        self.frame_4 = QtWidgets.QFrame(self.frame_14)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_edit = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit.sizePolicy().hasHeightForWidth())
        self.btn_edit.setSizePolicy(sizePolicy)
        self.btn_edit.setStyleSheet("QPushButton {\n"
"    color : #FFFFFF;\n"
"    border-style : solid;\n"
"    border-radius: 5px;\n"
"    min-height : 40px;\n"
"    font : 77 18px \"Arial\";\n"
"    background-color : orange;\n"
"    padding-left : 20px;\n"
"    padding-right : 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #FFF;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color : transparent;\n"
"    color : orange;\n"
"    border: 1px solid orange;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout_3.addWidget(self.btn_edit)
        self.btn_remove = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remove.sizePolicy().hasHeightForWidth())
        self.btn_remove.setSizePolicy(sizePolicy)
        self.btn_remove.setStyleSheet("QPushButton {\n"
"    color : #FFFFFF;\n"
"    border-style : solid;\n"
"    border-radius: 5px;\n"
"    min-height : 40px;\n"
"    font : 77 18px \"Arial\";\n"
"    background-color : red;\n"
"    padding-left : 20px;\n"
"    padding-right : 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #FFF;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color : transparent;\n"
"    color : red;\n"
"    border: 1px solid red;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout_3.addWidget(self.btn_remove)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_18.addWidget(self.fme_image_cap_2)
        self.fme_card_content_2 = QtWidgets.QFrame(self.fme_card_content_0)
        self.fme_card_content_2.setStyleSheet("")
        self.fme_card_content_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fme_card_content_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fme_card_content_2.setObjectName("fme_card_content_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fme_card_content_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.fme_card_content_2)
        self.frame_3.setStyleSheet("QFrame {\n"
"    border : none;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_11.setStyleSheet("QFrame {\n"
"    border : none;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("QLabel {\n"
"    font : 18px \"Arial\";\n"
"    color: #A0A0A0;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.ted_message = QtWidgets.QTextEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ted_message.sizePolicy().hasHeightForWidth())
        self.ted_message.setSizePolicy(sizePolicy)
        self.ted_message.setStyleSheet("QTextEdit {\n"
"    background-color: transparent;\n"
"    border : 1px solid;\n"
"    border-color: #CED7E6;\n"
"    border-radius: 7px;\n"
"    font : 17px \"Arial\";\n"
"}")
        self.ted_message.setObjectName("ted_message")
        self.verticalLayout_4.addWidget(self.ted_message)
        self.btn_send_message = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_message.sizePolicy().hasHeightForWidth())
        self.btn_send_message.setSizePolicy(sizePolicy)
        self.btn_send_message.setStyleSheet("QPushButton {\n"
"    color : #FFFFFF;\n"
"    border-style : solid;\n"
"    border-radius: 5px;\n"
"    min-height : 40px;\n"
"    font : 77 18px \"Arial\";\n"
"    background-color : #616161;\n"
"    padding-left : 20px;\n"
"    padding-right : 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #FFF;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color : transparent;\n"
"    color : #42B72A;\n"
"    border: 1px solid #616161;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.btn_send_message.setObjectName("btn_send_message")
        self.verticalLayout_4.addWidget(self.btn_send_message)
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.verticalLayout_5.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_18.addWidget(self.fme_card_content_2)
        self.verticalLayout.addWidget(self.fme_card_content_0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_card_title.setText(_translate("Form", "Product Name"))
        self.lbl_card_subtitle.setText(_translate("Form", "Category"))
        self.label.setText(_translate("Form", "Detalles"))
        self.ted_message_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:17px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_add_to_cart.setToolTip(_translate("Form", "Mostrar productos"))
        self.btn_add_to_cart.setText(_translate("Form", "Añadir al carrito"))
        self.btn_buy.setToolTip(_translate("Form", "Mostrar productos"))
        self.btn_buy.setText(_translate("Form", "Comprar"))
        self.btn_edit.setToolTip(_translate("Form", "Mostrar productos"))
        self.btn_edit.setText(_translate("Form", "Modificar"))
        self.btn_remove.setToolTip(_translate("Form", "Mostrar productos"))
        self.btn_remove.setText(_translate("Form", "Eliminar"))
        self.label_2.setText(_translate("Form", "Comentar o consultar"))
        self.ted_message.setPlaceholderText(_translate("Form", " Ingrese un comentario o alguna consulta en éste campo."))
        self.btn_send_message.setText(_translate("Form", "Comentar"))
import assets_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
