# -*- coding: utf-8 -*-
import datetime

# Form implementation generated from reading ui file 'gui\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

from mysqlhelper.Conector import Conexion
from controllers.MainWindow import UiMainWindow


class UiDialogSignup(object):
    def __init__(self, __application, __login):
        self.__application = __application
        self.__login = __login

    def setupUi(self, dialog):
        dialog.setObjectName("Dialog")
        dialog.resize(404, 438)
        dialog.setStyleSheet("QDialog {\n"
                             "    background-color : #FFF;\n"
                             "    margin : 0px;\n"
                             "    padding : 0px;\n"
                             "}\n"
                             "\n"
                             "QFrame#content {\n"
                             "    background-color : transparent;\n"
                             "    border: 1px solid #DADDE1;\n"
                             "    border-radius: 5px;\n"
                             "    min-width : 380px;\n"
                             "    min-height : 412px;\n"
                             "}\n"
                             "\n"
                             "QLabel {\n"
                             "    font : 77 12px \"Arial\";\n"
                             "    color : red;\n"
                             "}\n"
                             "\n"
                             "QLineEdit {\n"
                             "    background-color : transparent;\n"
                             "    border : 1px solid #DADDE1;\n"
                             "    border-radius : 5px;\n"
                             "    color : #616161;\n"
                             "    min-height : 40px;\n"
                             "    font : 77 18px \"Arial\";\n"
                             "}\n"
                             "\n"
                             "QPushButton {\n"
                             "    color : #FFFFFF;\n"
                             "    border-style : solid;\n"
                             "    border-radius: 5px;\n"
                             "    min-height : 40px;\n"
                             "    font : 77 18px \"Arial\";\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_login {\n"
                             "    background-color : #1877F2;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_login:pressed {\n"
                             "    background-color : transparent;\n"
                             "    color : #1877F2;\n"
                             "    border: 1px solid #1877F2;\n"
                             "    border-radius: 5px;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_signup {\n"
                             "    background-color : #42B72A;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_signup:hover, #btn_exit:hover, #btn_login:hover, #btn_cancel:hover {\n"
                             "    border: 1px solid #FFF;\n"
                             "    border-radius: 5px;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_signup:pressed {\n"
                             "    background-color : transparent;\n"
                             "    color : #42B72A;\n"
                             "    border: 1px solid #42B72A;\n"
                             "    border-radius: 5px;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_exit {\n"
                             "    background-color : #616161;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_exit:pressed {\n"
                             "    background-color : transparent;\n"
                             "    color : #616161;\n"
                             "    border: 1px solid #616161;\n"
                             "    border-radius: 5px;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_forgotten_password {\n"
                             "    border-style: outset;\n"
                             "    border-width: 0px;\n"
                             "    color : #1877F2;\n"
                             "    font : 77 15px \"Arial\";\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_forgotten_password:hover {\n"
                             "    text-decoration: underline;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_cancel {\n"
                             "    background-color : red;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_cancel:pressed {\n"
                             "    background-color : transparent;\n"
                             "    color : red;\n"
                             "    border: 1px solid red;\n"
                             "    border-radius: 5px;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_show_password, #btn_show_repassword {\n"
                             "    min-widgth : 32px;\n"
                             "    min-height : 32px;\n"
                             "}\n"
                             "\n"
                             "QPushButton#btn_show_password:hover, #btn_show_repassword:hover {\n"
                             "    background-color: #DADDE1;\n"
                             "}\n")

        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content = QtWidgets.QFrame(dialog)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_info = QtWidgets.QLabel(self.content)
        self.lbl_info.setObjectName("lbl_info")
        self.lbl_info.setStyleSheet("QLabel {\n"
                                    "    font : 77 12px \"Arial\";\n"
                                    "    color : green;"
                                    "}\n")
        self.verticalLayout_2.addWidget(self.lbl_info)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tfd_name = QtWidgets.QLineEdit(self.content)
        self.tfd_name.setClearButtonEnabled(True)
        self.tfd_name.setObjectName("tfd_name")
        self.verticalLayout_2.addWidget(self.tfd_name)
        self.tfd_surname = QtWidgets.QLineEdit(self.content)
        self.tfd_surname.setClearButtonEnabled(True)
        self.tfd_surname.setObjectName("tfd_surname")
        self.verticalLayout_2.addWidget(self.tfd_surname)
        self.tfd_email = QtWidgets.QLineEdit(self.content)
        self.tfd_email.setClearButtonEnabled(True)
        self.tfd_email.setObjectName("tfd_email")
        self.verticalLayout_2.addWidget(self.tfd_email)
        self.tfd_user = QtWidgets.QLineEdit(self.content)
        self.tfd_user.setClearButtonEnabled(True)
        self.tfd_user.setObjectName("tfd_user")
        self.verticalLayout_2.addWidget(self.tfd_user)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tfd_password = QtWidgets.QLineEdit(self.content)
        self.tfd_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tfd_password.setClearButtonEnabled(True)
        self.tfd_password.setObjectName("tfd_password")
        self.horizontalLayout_3.addWidget(self.tfd_password)

        self.btn_show_password = QtWidgets.QPushButton(self.content)
        self.btn_show_password.setText("")

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui\\../icon/candado-cerrado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_password.setIcon(icon)

        self.btn_show_password.setIconSize(QtCore.QSize(24, 24))
        self.btn_show_password.setObjectName("btn_show_password")
        self.horizontalLayout_3.addWidget(self.btn_show_password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tfd_repassword = QtWidgets.QLineEdit(self.content)
        self.tfd_repassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tfd_repassword.setClearButtonEnabled(True)
        self.tfd_repassword.setObjectName("tfd_repassword")
        self.horizontalLayout_2.addWidget(self.tfd_repassword)
        self.btn_show_repassword = QtWidgets.QPushButton(self.content)
        self.btn_show_repassword.setText("")
        self.btn_show_repassword.setIcon(icon)
        self.btn_show_repassword.setIconSize(QtCore.QSize(24, 24))
        self.btn_show_repassword.setObjectName("btn_show_repassword")
        self.horizontalLayout_2.addWidget(self.btn_show_repassword)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lbl_info2 = QtWidgets.QLabel(self.content)
        self.lbl_info2.setText("")
        self.lbl_info2.setObjectName("lbl_info2")
        self.verticalLayout_2.addWidget(self.lbl_info2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel = QtWidgets.QPushButton(self.content)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_signup = QtWidgets.QPushButton(self.content)
        self.btn_signup.setObjectName("btn_signup")
        self.horizontalLayout.addWidget(self.btn_signup)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.content)

        self.__setupUiComponents()

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Signup"))
        self.lbl_info.setText(_translate("Dialog", "* Rellene los campos para continuar con el registro."))
        self.tfd_name.setPlaceholderText(_translate("Dialog", " * Ingrese su nombre"))
        self.tfd_surname.setPlaceholderText(_translate("Dialog", " * Ingrese su apellido"))
        self.tfd_email.setPlaceholderText(_translate("Dialog", " * Ingrese su correo electronico"))
        self.tfd_user.setPlaceholderText(_translate("Dialog", " * Ingrese un usuario"))
        self.tfd_password.setPlaceholderText(_translate("Dialog", " * Ingrese una contraseña"))
        self.tfd_repassword.setPlaceholderText(_translate("Dialog", " * Vuelva a ingresar la contraseña"))
        self.btn_cancel.setText(_translate("Dialog", "Cancelar"))
        self.btn_signup.setText(_translate("Dialog", "Crear cuenta"))

    def __keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_Return or event.key() == QtCore.Qt.Key_Enter:
            self.__signup()

    def __setupUiComponents(self):
        self.content.keyPressEvent = self.__keyPressEvent
        self.btn_cancel.clicked.connect(self.__cancel)
        self.btn_signup.clicked.connect(self.__signup)

    def __cancel(self):
        self.__application.ui_config(QDialog(), self.__login)

    def __signup(self):
        if self.tfd_name.text() \
                and self.tfd_surname.text() \
                and self.tfd_user.text() \
                and self.tfd_email.text()\
                and self.tfd_password.text() \
                and self.tfd_repassword.text():
            self._connector = Conexion()
            if self._connector.is_connected():
                sql = "SELECT contrasenia FROM byesikch2cyefw2pvcqg.usuario WHERE id = '" + self.tfd_user.text() + "'"
                data = self._connector.run_query(sql)
                if data:
                    self.lbl_info.setStyleSheet("")
                    self.lbl_info.setText(" * ¡ERROR! El usuario ingresado ya esta en uso.")
                else:
                    if self.tfd_password.text() == self.tfd_repassword.text():
                        self.lbl_info.setStyleSheet("QLabel {\n"
                                                    "    font : 77 12px \"Arial\";\n"
                                                    "    color : green;"
                                                    "}\n")
                        self.lbl_info.setText(" * ¡CORRECTO! Puede registrarse.")
                        sql = "INSERT INTO `byesikch2cyefw2pvcqg`.`usuario` (`id`," \
                              " `nombre`," \
                              " `apellido`," \
                              " `id_tipo_usuario`," \
                              " `contrasenia`," \
                              " `fecha_acceso`," \
                              " `email`" \
                              " `admitido`" \
                              ") VALUES ('" + self.tfd_user.text() + "'," \
                              " '" + self.tfd_name.text() + "'," \
                              " '" + self.tfd_surname.text() + "'," \
                              " '2'," \
                              " '" + self.tfd_password.text() + "'," \
                              " NULL," \
                              " '" + self.tfd_email.text() + "'" \
                              " '0'," \
                              ")"
                        self._connector.run_query(sql)
                        date_time = str(datetime.datetime.now().strftime('%d/%m/%Y - %H:%M:%S'))
                        sql = "UPDATE `byesikch2cyefw2pvcqg`.`usuario`" \
                              " SET `fecha_acceso` = '" + date_time + "' WHERE (`id` = '" + self.tfd_user.text() + "');"
                        self._connector.run_query(sql)
                        self.__application.user = self.tfd_user.text()
                        self._connector.close()
                        self.__application.ui_config(QtWidgets.QMainWindow(), UiMainWindow(self.__application, self.__login))
                    else:
                        self.lbl_info.setStyleSheet("")
                        self.lbl_info.setText(" * ¡ERROR! Las contraseñas no coinciden.")
            else:
                self.lbl_info.setStyleSheet("")
                self.lbl_info.setText(" * ¡ERROR! No se pudo realizar la coneccion.")
        else:
            self.lbl_info.setStyleSheet("")
            self.lbl_info.setText(" * ¡ERROR! Los campos no pueden estar vacios.")